### ISSUE TITLE
Add a way to prepare update Queries

### ISSUE THREAD

**Issue by schmitch** [finagle/finagle-postgres#13]
Hello, currently it is impossible to prepare a update query, this could lead to insecure code.
I think somehow it would be great to have a similar API than [Anorm](https://github.com/playframework/anorm/blob/master/docs/manual/working/scalaGuide/main/sql/ScalaAnorm.md) where you could "prepare" a query via `SQL""` or `SQL""""""` and use string interpolation directly.

Also it doesn't look to hard to have a feature like that. 
However the main purpose should be an alternative to `executeUpdate(str: String)`so that we can INSERT or UPDATE without strings, which are easily attackable to SQL injections.

**Comment by vkostyukov** [comment]
Fixed by #10.
