### ISSUE TITLE
Implementing Postgres Client in terms of StackClient?

### ISSUE THREAD

**Issue by jnd71** [finagle/finagle-postgres#4]
Would this project be interested in a newer `PostgresClient` that's implemented in terms of the `StackClient`, al lá [finagle-mysql](https://github.com/twitter/finagle/blob/master/finagle-mysql/src/main/scala/com/twitter/finagle/Mysql.scala)?  I ask first instead of a PR because implementing the new `PostgresClient` would require either breaking changes on `com.twitter.finagle.postgres.Client`, or duplicating behavior into a newer client and sunsetting / leaving the original `com.twitter.finagle.postgres.Client`.  

Thoughts?

**Comment by travisbrown** [comment]
This sounds like a good idea to me—once you've got a PR I'll work with @yolken to see about getting it merged internally, and if for some reason it seems like it won't be possible to do that in a timely fashion, I'll  set up a new branch here for tracking the internal project.
