### ISSUE TITLE
finagle-postgres version for scala 2.10

### ISSUE THREAD

**Issue by ponkin** [finagle/finagle-postgres#41]
Are there any plans to create version for scala 2.10? I did not find any available jar in maven repositories.

**Comment by taylorleese** [comment]
See https://finagle.github.io/blog/2016/04/20/scala-210-and-java7/.

**Comment by jeremyrsmith** [comment]
@pokin as @taylorleese pointed out, it won't be possible to support scala 2.10 anymore due to finagle dropping support for it. Sorry about that!
