### ISSUE TITLE
Exception in thread main

### ISSUE THREAD

**Issue by milnomada** [finagle/finagle-postgres#63]
Hello,

Testing a simple connection to a local postgresql  instance with Scala 2.11, I got this exception:
**Exception in thread "main" java.lang.AbstractMethodError: com.twitter.finagle.stats.MetricsStatsReceiver.com**

**stacktrace**
[error] 	at com.twitter.finagle.stats.StatsReceiverWithCumulativeGauges$class.$init$(CumulativeGauge.scala:133)
[error] 	at com.twitter.finagle.stats.MetricsStatsReceiver.<init>(MetricsStatsReceiver.scala:175)
[error] 	at com.twitter.finagle.stats.MetricsStatsReceiver.<init>(MetricsStatsReceiver.scala:179)
[error] 	at com.twitter.finagle.stats.MetricsStatsReceiver.<init>(MetricsStatsReceiver.scala:180)
[error] 	at com.twitter.finagle.stats.MetricsStatsReceiver.<init>(MetricsStatsReceiver.scala:181)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error] 	at java.lang.Class.newInstance(Class.java:442)
[error] 	at com.twitter.app.LoadService$$anonfun$5.apply(LoadService.scala:74)
[error] 	at com.twitter.app.LoadService$$anonfun$5.apply(LoadService.scala:63)
[error] 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
[error] 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
[error] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
[error] 	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] 	at com.twitter.app.LoadService$.apply(LoadService.scala:63)
[error] 	at com.twitter.finagle.util.LoadService$.apply(LoadService.scala:14)
[error] 	at com.twitter.finagle.stats.LoadedStatsReceiver$.<init>(LoadedStatsReceiver.scala:18)
[error] 	at com.twitter.finagle.stats.LoadedStatsReceiver$.<clinit>(LoadedStatsReceiver.scala)
[error] 	at com.twitter.finagle.stats.ClientStatsReceiver$.<init>(LoadedStatsReceiver.scala:47)
[error] 	at com.twitter.finagle.stats.ClientStatsReceiver$.<clinit>(LoadedStatsReceiver.scala)
[error] 	at com.twitter.finagle.client.StackClient$.<init>(StackClient.scala:389)
[error] 	at com.twitter.finagle.client.StackClient$.<clinit>(StackClient.scala)
[error] 	at com.twitter.finagle.Postgres$.com$twitter$finagle$Postgres$$defaultStack(Postgres.scala:69)
[error] 	at com.twitter.finagle.Postgres$Client$.apply$default$1(Postgres.scala:96)
[error] 	at com.example.finatrabasics.controllers.testSuite$.main(DbController.scala:63)
[error] 	at com.example.finatrabasics.controllers.testSuite.main(DbController.scala)

It happens trying the example client connection you have on your [quickstart page](https://finagle.github.io/finagle-postgres/doc/02-basic-usage.html) 

```
val client = Postgres.Client()
        .withCredentials("user", Some("pass"))
        .database("mydb")
        .newRichClient("localhost:5432")
```

Just creating this issue in case your team would like someone succesfully using this library with newer versions of Scala.

**Comment by jeremyrsmith** [comment]
This looks like an issue with clashing finagle versions. We've just updated to (I think) the latest version of finagle, so that should solve this issue (assuming you're also using the latest version of finagle/finatra)
