### ISSUE TITLE
Finagle is going to be dropping finagle-netty3

### ISSUE THREAD

**Issue by bryce-anderson** [finagle/finagle-postgres#70]
The Finagle library is finishing up its transition to Netty4, and as such it's going to be dropping Netty3 support in its entirety at some point. However, it looks like `finagle-postgres` is heavily dependent on the `finagle-netty3` package.

There are at least two roads forward.
1. `finagle-postgres` can migrate to finagle-netty4.
2. The `finagle-netty3` package could be moved to the finagle org.

These are not mutually exclusive, but either will address the issue at hand. Do you have a preference? There may be enough ecosystem projects to justify the second route regardless but we haven't don't an extensive survey.

**Comment by leonmaia** [comment]
Thanks, @bryce-anderson for the heads up. I'll try to take a look on how many changes we need to do to migrate to `finagle-netty4` but of course, if we can also do the second route would be nice since it would give us more time to work on the transition.

**Comment by jeremyrsmith** [comment]
@bryce-anderson I opened #74 to tackle the upgrade. It'd be great if you could take a look and let me know if I've done anything terribly wrong with respect to the change (I took the shortest path that made sense, so there's still a lot of old code which isn't the best... but hopefully it will get the job done)

**Comment by bryce-anderson** [comment]
Awesome! I'll take a look today. It looks like @vkostyukov is looking as well.

**Comment by vkostyukov** [comment]
Bumping this up.

@leonmaia @jeremyrsmith I think we're couple of months away from stopping publishing finagle-netty3. I know there is some progress was done in #74 to migrate to finagle-netty4. Let me know if there is anything I can do to help.

**Comment by vkostyukov** [comment]
Hey! Just wanted you let you all know that we're not going to publish finagle-netty3 in the next release (19.4). This means finagle-postgres would need to stay on 19.3 until it's migrated to finagle-netty4.

**Comment by leonmaia** [comment]
I'll go ahead and close this issue since we already migrated to `finagle-netty4`.
