### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by clhodapp** [finagle/finagle-postgres#85]
Hey! I know that the administrative tasks of being an open-source maintainer can be a severe drain on one's personal energy level and that this ticket is probably going to induce at least a slight internal groan but... It would be great to get a new release. The issue in https://github.com/finagle/finagle-postgres/pull/81 is severe enough for my use-case that I've been running a build from the source of master in order to get the fix but it would be great to be able to use a proper upstream binary release. I do also think that pretty much anyone using finagle-postgres in production ought to get that fix because it can cause very difficult-to-diagnose query failures.

**Comment by vkostyukov** [comment]
Hey @clhodapp! Sorry the project feels abandoned. Please, reach out if you're actively using it and would like to step up as a maintainer.

I will cut a release this weekend.

**Comment by clhodapp** [comment]
@vkostyukov Yes please. The more (responsible) folks have maintainer abilities on time-strapped projects like this the better, in my opinion.

**Comment by jeremyrsmith** [comment]
👍 agreed (and the more maintainers that actually use the library, the better maintained it will be!)

**Comment by jeremyrsmith** [comment]
And anyone who can manage to actively maintain this project is welcome to take the "current maintainer" mantle in the README, FWIW 😀

**Comment by clhodapp** [comment]
Ping

**Comment by leonmaia** [comment]
@clhodapp I'll be doing a release later today.

**Comment by clhodapp** [comment]
@leonmaia Thanks so much!
