### ISSUE TITLE
queryDSL  `as` method 

### ISSUE THREAD

**Issue by FunkyYang** [finagle/finagle-postgres#88]
Hi:
I meet a problem with use queryDSL spec
```
val resultFuture = sql"select count(*) as toal from tableA".as[Count].run(postgresClient)

the Count be defined like this below

case class Count(total:Int =0)

and then 

   val resultSeq = Await.result(resultFuture, Duration(10, TimeUnit.SECONDS))
    val total = if (resultSeq.isEmpty) 0 else resultSeq.head.total

````
but not found in case class Count ,the  total is always 0

**Comment by FunkyYang** [comment]
I see the type mapper and find postgres type ``bigint``` convert scala type is ```BigDecimal``` ,how could me convert it to scala type ```Long```

**Comment by leonmaia** [comment]
@FunkyYang I believe this is related to #82. I'm not with a ton of time right now to work on this project so, I'm sorry for the late response. Please feel free to open a PR in case you find the root cause, in case it's not that urgent for you that is already in my personal backlog to tackle ASAP.

**Comment by leonmaia** [comment]
Hi @FunkyYang how is your client configuration?

**Comment by leonmaia** [comment]
Please have a look at the resolution of issue #82, please let me know if the reason was having `.withBinaryResults(true)` as one of the client configurations.

**Comment by leonmaia** [comment]
Please feel free to reopen this if my previous response hasn't solved your issue. 😊
