### ISSUE TITLE
DELETE...RETURNING causes an error

### ISSUE THREAD

**Issue by jeremyrsmith** [finagle/finagle-postgres#9]
There is no state transition from AggregateRowsWithoutFields when a Delete(_) tag is received (though it exists for Update(_)).  This makes DELETE...RETURNING queries impossible.

**Comment by jeremyrsmith** [comment]
Error is: Unknown event CommandComplete(Delete(1))

which leads to

Unknown event com.twitter.finagle.postgres.messages.Sync$@568841ee for state AggregateRowsWithoutFields

**Comment by vkostyukov** [comment]
Fixed by #10.
