### ISSUE TITLE
Setup Autoreleases

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finagle-postgres#92]
@leonmaia @jeremyrsmith I had a great success with setting up autorelease for Finch-related projects (also finagle-oauth2). I'm happy to volunteer and do the same for finagle-postgress. The end goal is to allow anyone with push access to the repo perform releases with just changing (and committing) a new version in `version.sbt`.

What do you think about this?

**Comment by jeremyrsmith** [comment]
👍 from me. Whatever helps this project get the maintenance it needs (appreciate @leonmaia's stewardship, but it looks like he might be in the same boat as me w.r.t. free time)

**Comment by leonmaia** [comment]
Would be awesome @vkostyukov! I'm all in to do less manual work. Let me know if you need any help with it!

**Comment by vkostyukov** [comment]
Cool - I can give it a try. The key idea is to have the following credentials available (and encrypted):

 - `credentials.sbt` - sonatype password + gpg passphrase
 - `deploy_key` (this is needs to be generated for a repo - easy to do)

I believe I have write access to pretty much all repos under this org so I can use my credentials.

**Comment by vkostyukov** [comment]
Done in #102.
